profiles:
  huggingface:
    guardrail_name: harm_guard
    provider:
      type: huggingface

  llamafile:
    guardrail_name: any_llm
    validate_kwargs:
      model_id: openai:llamafile
      api_base: http://llamafile.guardrails.example.com:8080/v1

  encoderfile:
    guardrail_name: any_llm
    validate_kwargs:
      model_id: openai:encoderfile
      api_base: http://encoderfile.guardrails.example.com:8080/v1
